### ISSUE TITLE
NuKeeper tries to update from stable to beta with UsePrerelease=FromPrerelease

### ISSUE THREAD

**Issue by kipusoep** [NuKeeperDotNet/NuKeeper#1111]
## 🐛 Bug Report

We're using NuKeeper with Azure DevOps pipelines and there seems to be an issue regarding UsePrerelease.
The job itself looks like this:
```
# Update nuget packages that have minor changes and are available for a week.
- task: NuKeeper@0
  displayName: "NuKeeper Minor"
  inputs:
    version: '0.*'
    arguments: '--change minor --maxpackageupdates 9999 --consolidate true --branchnameprefix nukeeper/minor/'
```
As we're not explicitly setting the `UsePrerelease` argument, it should be set to `FromPrerelease` by default.
Still a package update is suggested from a stable version to an unstable version:
> StyleCop.Analyzers to 1.2.0-beta.354 from 1.1.118

Why is this happening?

### Expected behavior
I'd expect NuKeeper not to update this package to an unstable version from a stable version.

### Reproduction steps
See job description above.

### Configuration

```
Task         : NuKeeper
Description  : Version 0.4.43
Version      : 0.4.43
```

**Platform if applicable:** 
- [ ] :hammer_and_wrench: NuKeeper CLI
- [ ] :sparkles: GitHub
- [X] :robot: AzureDevops
- [ ] :checkered_flag: Bitbucket
- [ ] :earth_americas: Gitlab
- [ ] :tv: Gitea
- [ ] :whale: Docker
